# Generated by Django 5.1.3 on 2024-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='yop',
            field=models.IntegerField(),
        ),
    ]
